### ISSUE TITLE
Fail better with non UTF-8 encodings

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#672] opened 2015-11-15 19:56 UTC
Currently either input is frozen (#498, #362), or a segfault can occur (#670) when the LANG is not set to a UTF-8 encoding.

Until non UTF-8 compatibility is implemented (#248), either fail with a useful message, or try to handle characters better.

**Comment by jubalh** [comment] 2022-04-01 10:44
@paulfertser do you maybe have an idea about this one?

**Comment by jubalh** [comment] 2022-04-04 21:53
@paulfertser wanted to take a look at this and asked in the MUC how to reproduce it. Since for him it worked. The two people who suffered from this seemed to not know how or didn't have the time.
So closing this.

**Closed by jubalh** 2022-04-04 21:53 UTC
Labels: bug
