### ISSUE TITLE
messages (OMEMO) offline

### ISSUE THREAD

**Issue by nolash** [profanity-im/profanity#1025] opened 2018-12-07 00:15 UTC
Can profanity receive messages sent to an account while if was offline? If there is a difference in offline message handling (I'm not so familiar with XMPP extensions), I mean OMEMO-messages specifically.

Also, which would be the relevant XEPs for such capability, if you happen to know?

**Comment by pasis** [comment] 2018-12-07 09:54
Yes, it does. Such messages have additional tag described in respective XEPs. Check these:
 * https://xmpp.org/extensions/xep-0160.html
 * https://xmpp.org/extensions/xep-0091.html
 * https://xmpp.org/extensions/xep-0203.html

Exact place in the code where such a message is handled: `src/xmpp/message.c::_handle_chat()` and `src/xmpp/stanza.c::stanza_get_delay()`. Profanity checks if a message is delayed and further uses only timestamp to display when it was sent.

As I can see from [XEP-OMEMO](https://conversations.im/omemo/xep-omemo.html), it uses just a message stanza, so I expect the message can be delayed. The problem is in keys, sessions, etc. I'm not familiar with OMEMO, but I suppose messages may have some attributes that are valid only within a particular session. Second problem is with plugins, since OMEMO message contains `<encrypted>` tag instead of `<body>`, I don't know how it can be handled (I mean, I'm not familiar with plugins implementation).

**Comment by jubalh** [comment] 2019-02-19 18:05
As I understand it this was a just a general question. Anything in particular you were trying to find out, @nolash ?
Can we close this issue?

**Comment by jubalh** [comment] 2019-02-19 18:10
@pasis should we also list such XEPs at http://profanity.im/xeps.html ? I think usually clients dont list them but maybe it would be more complete that way.

**Comment by pasis** [comment] 2019-03-22 07:06
@jubalh As I see, you have already added XEP-203 to the page. So yes, it's a good idea.

**Comment by pasis** [comment] 2019-03-22 07:12
Here is an example of delayed OMEMO message: [[1]](https://discourse.igniterealtime.org/t/smack-omemo-rework-177-during-omemo-muc-messging-setup-and-sending-message-omemoratchet-always-throws-cryptofailedexception-etc/80533) (check the 1st received message).

**Comment by jubalh** [comment] 2019-03-22 09:26
> @jubalh As I see, you have already added XEP-203 to the page. So yes, it's a good idea.

Actually I didn't do that. It's there since always:
https://github.com/boothj5/www_profanity_im/commit/394fd8cffab319c3a1b24575903c7a5fdffb4904#diff-aab5a58fec438b8f6d9f6ac6da2051cd

**Comment by jubalh** [comment] 2019-06-11 04:56
Added the XEPs to the website. Assuming this issue is solved now.

**Closed by jubalh** 2019-06-11 04:56 UTC
Labels: question
