### ISSUE TITLE
MUC screen flush after reconnect

### ISSUE THREAD

**Issue by equation-group** [profanity-im/profanity#1636] opened 2022-02-05 16:38 UTC
## Expected Behavior
It should not flush screen on auto disconnect and after reconnect

## Current Behavior
It flushes the screen i.e. empty chat in muc,  You have joined the room as (null), role: none, affiliation: none" 
after reconnect 

## Possible Solution
I don't know, there is some issue with last message time comparison

## Steps to Reproduce (for bugs)

1. join a muc
2. chat for some time, then turn off internet it will disconnect , i assume /reconnect 30s timeout
3. turn on internet and it will reconnect
4. now, check the muc, the chat screen is smoty

## Environment
   Profanity, version 0.11.1

##Error  Log
stderr: ERR: (profanity:22): GLib-CRITICAL **: 23:17:22.485: g_date_time_difference: assertion 'end != NULL' failed
 stderr: ERR: (profanity:22): GLib-CRITICAL **: 23:17:22.486: g_date_time_difference: assertion 'end != NULL' failed
stderr: ERR: (profanity:22): GLib-CRITICAL **: 23:17:22.898: g_date_time_difference: assertion 'end != NULL' failed
stderr: ERR: (profanity:22): GLib-CRITICAL **: 23:17:22.899: g_date_time_difference: assertion 'end != NULL' failed
.... similar more

**Comment by mdosch** [comment] 2022-02-05 16:40
There's already an issue for this problem but I didn't find it now as mobile github sucks.

**Comment by jubalh** [comment] 2022-02-05 17:50
duplicate of https://github.com/profanity-im/profanity/issues/1556

**Closed by jubalh** 2022-02-05 17:50 UTC
