### ISSUE TITLE
[OMEMO] profanity should fix the PEP access model if wrongly configured by another client

### ISSUE THREAD

**Issue by g4570n** [profanity-im/profanity#1538] opened 2021-05-26 01:36 UTC
Me and my friend use the same version of profanity, we both have two OMEMO keys, one from another client and one created in profanity. When we do `/omemo fingerprint <account>` we only get the fingerprint of another client, but the profanity of the other is not listed. 

But if we both do: `/omemo fingerprint` in the console, if the hash of profanity and that of the other client we use come out

I followed the steps detailed here: https://github.com/profanity-im/blog/blob/master/content/post/omemo.md , but it only lists one of the IDs of your mobile device but not that of your profanity client.

When we want to use Omemo and he writes to me from his profanity client I get this message: "You received a message encrypted with OMEMO but your client doesn't support OMEMO." `¯\_(ツ)_/¯`

```
$ uname -a
OpenBSD 6.9 GENERIC#464 amd64

$ profanity --version
Profanity, version 0.10.0
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libmesode
Desktop notification support: Disabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.15.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.8.8)
GTK icons: Disabled
```

**Comment by ffuentese** [comment] 2021-05-26 01:52
Also it's not possible to add the other device's fingerprint because it's "unknown"

**Comment by DebXWoody** [comment] 2021-05-26 04:15
Hello,
I'm working on OMEMO bug-squashing. Feel free to join the party ;-) I would like to check some things with you.

Is the device listed in the file `~/.local/share/profanity/omemo/<YOUR_JID>/known_devices.txt`?

**Comment by g4570n** [comment] 2021-05-26 05:15
> Is the device listed in the file `~/.local/share/profanity/omemo/<YOUR_JID>/known_devices.txt`?

At the beginning of this file are listed mine, both, Gajim's and profanity's. But of my buddy's devices, there is only one listed there

**Comment by DebXWoody** [comment] 2021-05-26 07:49
Use `/xmlconsole` to open the XML Console.

Prepare the following line ( set `from` and `to` attributes) (one line!)

`
<iq type='get' from='your@domain.tld' to='buddy@domain.tld' id='getOmemoDeviceList'><pubsub xmlns='http://jabber.org/protocol/pubsub'><items node='eu.siacs.conversations.axolotl.devicelist'/></pubsub></iq>
`

Send this **one** line via the `xmlconsole`. https://github.com/profanity-im/blog/blob/master/content/post/omemo.md#debugging
You should get a `result` or an `error` with the id `getOmemoDeviceList` as response.

- Do you get an error response?
- Do you get a list of devices?
- How may devices are in the response?

**Comment by g4570n** [comment] 2021-05-26 14:43
> * Do you get an error response?

No.

> * Do you get a list of devices?

Yes.

> * How many devices are in the response?

One device.

**Comment by g4570n** [comment] 2021-05-26 18:46
Ok, after doing what you ask me, I received a huge piece of text in response, is there something I should do with that?

**Comment by DebXWoody** [comment] 2021-05-26 19:22
No,... we don't care about the content. ;-)
It seems the key has been generated and are also stored on PEP. That is fine.
But, the device is not listed in the device list. This may happen if you clean the device list.

Maybe it will be fixed if you clean the device list from profanity `/omemo clear_device_list` and login via (Conversations?).
( But I'm not sure).

**Comment by mwuttke97** [comment] 2021-05-26 19:30
> Profanity, version 0.10.0

Perhaps you could try to compile and run the git `master` version. I think there was an issue with publishing the devlist (and I'm sure that I touched this code). We have also resolved a couple of other OMEMO-related issues, so trying the `master` version is really worth it if you want to use OMEMO.

**Comment by jubalh** [comment] 2021-05-26 19:44
Once we have found the last OMEMO issues I will create a 0.11.0 release so that this stuff reaches users.

**Comment by g4570n** [comment] 2021-05-26 19:51
> Maybe it will be fixed if you clean the device list from profanity `/omemo clear_device_list` and login via (Conversations?).
> ( But I'm not sure).

to see if I understand you. Do you want me to run: `/omemo clear_device_list` on the console, and then I log out of Profanity and log in from my other client (Gajim)?

**Comment by g4570n** [comment] 2021-05-27 00:17
My buddy and I tried to add each other's Profanity client fingerprints manually in the `known_devices.txt` file, like this:

He passed me his device ID and fingerprint, and I did the same with him. I opened the file `known_devices.txt` and added it below your account name like this:

```
[buddy@domain.tld]
1122334474=kh45jkh4jkh435j43h5jk43h5345jk436hk36jkjkewtwkej6ti546wketkwe (1)
1699887786=65765765n7jk65n7jknksfgdsfgysdgh98sdgfjksgfdnsdngjksgjksdjk56 (2)
```

`(1)` This was already in the list, it is the ID of the mobile device (Blabber), the only one that profanity recognizes / sees
`(2)` Here below I manually added the ID=fingerprint that my buddy gave me.

Then when I do: `/omemo fingerprint` now I get the key that I did not see before, and then I can do: `/omemo trust <fingerprint>`

Now all the keys are marked as trusted, if I look at the `known_devices.txt` file, I see it listed. If I look at the `trust.txt` file, both IDs also appear, but we are both still unable to decrypt the messages we send encrypted with Omemo from profanity, we still get the message: _"You received a message encrypted with OMEMO but your client doesn't support OMEMO."_

I ran the line that you had previously passed me in the XML console again, and the result on both sides was that you only see one ID of the other.

`<iq type='get' from='your@domain.tld' to='buddy@domain.tld' id='getOmemoDeviceList'><pubsub xmlns='http://jabber.org/protocol/pubsub'><items node='eu.siacs.conversations.axolotl.devicelist'/></pubsub></iq>`

```
<iq id="getOmemoDeviceList" type="result" to="your@domain.tld/profanity.6vUo" from="buddy@domain.tld">
<pubsub xmlns="http://jabber.org/protocol/pubsub">
<items node="eu.siacs.conversations.axolotl.devicelist">
    <item id="current">
    <list xmlns="eu.siacs.conversations.axolotl"><device id="1122334474"/></list>
    </item>
</items>
</pubsub>
</iq>
```
The result my buddy gets:

```
<iq id="getOmemoDeviceList" to="your@domain.tld/profanity.HfRD" type="result" from="buddy@domain.tld">
<pubsub xmlns="http://jabber.org/protocol/pubsub">
<items node="eu.siacs.conversations.axolotl.devicelist">
    <item id="630799EB26821">
    <list xmlns="eu.siacs.conversations.axolotl"><device id="491234560"/></list>
    </item>
</items>
</pubsub>
</iq>
```
That device ID (491234560) of mine that my friend gets is my Gajim client.


_* The device IDs and fingerprints I used here are illustrative._

**Comment by DebXWoody** [comment] 2021-05-27 04:15
> > Maybe it will be fixed if you clean the device list from profanity `/omemo clear_device_list` and login via (Conversations?).
> > ( But I'm not sure).
> 
> to see if I understand you. Do you want me to run: `/omemo clear_device_list` on the console, and then I log out of Profanity and log in from my other client (Gajim)?

Normally, but I didn't check it in details, it should work like this:
 * If you clean-up the device list, the client should re-announce his device ( profanity *should* set this device after clean
 * If you restart gajim, the client should add this device to the list
 * ...

I think, we may have an issue if you to it in the other way:
 * If you clean-up the device list via gajim
 * We may no not  re-announce the device in profanity (maybe)

Please do not add things, manually. We need to find the bug to squash them :-D Thanks for supporting to find those bugs.

Maybe the clean-up could solve the problem, but I will also try to prepare a XML stanza for you ( maybe tonight)

**Comment by g4570n** [comment] 2021-05-27 04:35
I already ran the `/omemo clear_device_list` command in Profanity and that didn't change anything, the ID of my buddy's profanity client still doesn't appear. Neither the ID of mine appears in the client profanity of him.

The problem is between profanitys clients, my buddy's and mine, which are not recognized. From my profanity client I have been able to chat with other different clients using Omemo without problems

**Comment by mwuttke97** [comment] 2021-05-27 07:42
On 27/05/2021 06:35, g4570n wrote:
> I already ran the |/omemo clear_device_list| command in Profanity and 
> that didn't change anything, the ID of my buddy's profanity client still 
> doesn't appear. Neither the ID of mine appears in the client profanity 
> of him.
> 
> The problem is between profanitys clients, my buddy's and mine, which 
> are not recognized. From my profanity client I have been able to chat 
> with other different clients using Omemo without problems
> 

Just to be sure, have you already tried the `git master` version? If 
not, we may stumble upon the same OMEMO issues again and again...

I am pretty sure that I had similar (reproduceable) issues with the 
release, but publishing the device list seems to work now 
(reproduceably) in `master`.


> Ok, after doing what you ask me, I received a huge piece of text in response, is there something I should do with that?

The "huge piece of text" is an "OMEMO bundle". This contains a set of 
public keys associated to your "OMEMO device id". However, before a 
client can request a bundle, it first has to know the device id.

**Comment by g4570n** [comment] 2021-05-27 17:23
> Just to be sure, have you already tried the `git master` version? If not, we may stumble upon the same OMEMO issues again and again... I am pretty sure that I had similar (reproduceable) issues with the release, but publishing the device list seems to work now (reproduceably) in `master`.

I have not compiled Profanity, I have the version available through the OpenBSD package.
https://openports.se/net/profanity

```
$ pkg_info -Q profanity
profanity-0.10.0p0 (installed)
```

**Comment by DebXWoody** [comment] 2021-05-28 18:12
> I already ran the `/omemo clear_device_list` command in Profanity and that didn't change anything, the ID of my buddy's profanity client still doesn't appear. Neither the ID of mine appears in the client profanity of him.

If you run the `clear_device_list` your buddy should see your device. It will not change your buddy's list, it should change your list.
Can you check if this solved the issue on your side? Your device id should be in your device id list.

**Comment by g4570n** [comment] 2021-05-28 19:29
> If you run the `clear_device_list` your buddy should see your device. It will not change your buddy's list, it should change your list.
> Can you check if this solved the issue on your side? Your device id should be in your device id list.

Please describe the correct process to follow, I just have to execute the `/omemo clear_device_list` command on my side... and that's it? Then my buddy will be able to see my device from the other side in his profanity client? 

Remember I told you earlier that we both have IDs and fingerprints added manually, keep that in mind.

**Comment by DebXWoody** [comment] 2021-05-29 08:07
- You: /omemo clear_device_list
- Profanity should set your device id in your device id list
- Your buddy: `/msg <your jid>` check the fingerprints via `/omemo fingerprint`

There are 4 files for OMEMO ( `identity.txt` `known_devices.txt`  `sessions.txt`  `trust.txt` ).
I don't know which files you have changed. Maybe it's better to start from beginning.

**Comment by g4570n** [comment] 2021-05-29 17:19
Here (https://github.com/profanity-im/profanity/issues/1538#issuecomment-849205206) I comment that the file that we modify manually is: `known_devices.txt`

**Comment by ffuentese** [comment] 2021-05-29 21:28
>     * You: /omemo clear_device_list
> 
>     * Profanity should set your device id in your device id list
> 
>     * Your buddy: `/msg <your jid>` check the fingerprints via `/omemo fingerprint`
> 
> 
> There are 4 files for OMEMO ( `identity.txt` `known_devices.txt` `sessions.txt` `trust.txt` ).
> I don't know which files you have changed. Maybe it's better to start from beginning.

I'm the buddy and I did the same things and I don't see him. It's as if profanity is not broadcasting the fingerprint. 

I'd try reproducing the issue with other people.  Both using the same version of profanity.

**Comment by g4570n** [comment] 2021-05-29 21:34
> * You: /omemo clear_device_list
> * Profanity should set your device id in your device id list
> * Your buddy: `/msg <your jid>` check the fingerprints via `/omemo fingerprint`

My buddy keeps seeing only one fingerprint, Gajim's, Profanity's doesn't come out. 

You should try to test using version 10 to see if you can reproduce this problem.

**Comment by DebXWoody** [comment] 2021-05-30 07:42
@jubalh Please add label "bug"

**Comment by DebXWoody** [comment] 2021-05-30 07:50
After I did a `/omemo clear_device_list` profanity didn't announce his device.
I restarted profanity and profanity pushed his device id. 1 this we should push the device id just after clean_device.

**Comment by DebXWoody** [comment] 2021-05-30 07:52
Is it possible to build profanity master? Do not use XMPP library: libmesode, please build with `libstrophe`.

**Comment by DebXWoody** [comment] 2021-05-30 09:01
@ffuentese @g4570n You can also ping me via groupchat

This stanza should set your own device list. You can try to set your device ids:

```
<iq id="setMyDevice" type="set"><pubsub xmlns="http://jabber.org/protocol/pubsub">
<publish node="eu.siacs.conversations.axolotl.devicelist"><item id="current"><list xmlns="eu.siacs.conversations.axolotl">
<device id="1312003422"/>
<device id="907785502"/>
</list></item></publish><publish-options><x xmlns="jabber:x:data" type="submit"><field type="hidden" var="FORM_TYPE"><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var="pubsub#access_model"><value>open</value></field></x></publish-options></pubsub></iq>
```

**Comment by g4570n** [comment] 2021-05-30 15:37
> This stanza should set your own device list. You can try to set your device ids:
> 
> ```
> <iq id="setMyDevice" type="set"><pubsub xmlns="http://jabber.org/protocol/pubsub">
> <publish node="eu.siacs.conversations.axolotl.devicelist"><item id="current"><list xmlns="eu.siacs.conversations.axolotl">
> <device id="1312003422"/>
> <device id="907785502"/>
> </list></item></publish><publish-options><x xmlns="jabber:x:data" type="submit"><field type="hidden" var="FORM_TYPE"><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var="pubsub#access_model"><value>open</value></field></x></publish-options></pubsub></iq>
> ```

I changed the IDs to those of my two clients and sent this via the `/xmlconsole`, and I got an error response:

```
<iq id="setMyDevice" type="error" to="my@domain.tld/profanity.6vUo"     
           lang="en" from="my@domain.tld"><pubsub                                  
           xmlns="http://jabber.org/protocol/pubsub"><publish                        
           node="eu.siacs.conversations.axolotl.devicelist"><item id="current"><list 
           xmlns="eu.siacs.conversations.axolotl"><device id="490123460"/><device    
           id="2061230574"/></list></item></publish><publish-options><x              
           xmlns="jabber:x:data" type="submit"><field type="hidden" var="FORM_TYPE"><
           value>http://jabber.org/protocol/pubsub#publish-options</value></field><fi
           eld var="pubsub#access_model"><value>open</value></field></x></publish-opt
           ions></pubsub><error code="409" type="cancel"><precondition-not-met       
           xmlns="http://jabber.org/protocol/pubsub#errors"/><conflict               
           xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>
```

**Comment by DebXWoody** [comment] 2021-05-30 17:24
I think I got it!
When we update / send the device list, we also adding `<publish-options/>` to set the `pubsub#access_model` to `open`.
When the node exists, we will get a `<precondition-not-met/>` if the existing node doesn't have open as access_model.
> see: https://xmpp.org/extensions/xep-0060.html#publisher-publish-options.

I guess the `access_model` is not set to open. You can request the configuration via:

```
<iq xmlns="jabber:client" type="get" id="getMetaConfig">
  <pubsub xmlns="http://jabber.org/protocol/pubsub#owner">
    <configure node="eu.siacs.conversations.axolotl.devicelist" />
  </pubsub>
</iq>
```

```
<field type="list-single" var="pubsub#access_model" label="Specify the subscriber model">
  <option label="authorize"><value>authorize</value></option>
  <option label="open"><value>open</value></option>
  <option label="presence"><value>presence</value></option>
  <option label="roster"><value>roster</value></option>
  <option label="whitelist"><value>whitelist</value></option>
<value>open</value>
```
I think you `<value/>` is not `open`?

**Comment by g4570n** [comment] 2021-05-30 22:03
> I guess the `access_model` is not set to open. You can request the configuration via:
> 
> ```
> <iq xmlns="jabber:client" type="get" id="getMetaConfig">
>   <pubsub xmlns="http://jabber.org/protocol/pubsub#owner">
>     <configure node="eu.siacs.conversations.axolotl.devicelist" />
>   </pubsub>
> </iq>
> ```
> 
> ```
> <field type="list-single" var="pubsub#access_model" label="Specify the subscriber model">
>   <option label="authorize"><value>authorize</value></option>
>   <option label="open"><value>open</value></option>
>   <option label="presence"><value>presence</value></option>
>   <option label="roster"><value>roster</value></option>
>   <option label="whitelist"><value>whitelist</value></option>
> <value>open</value>
> ```
> 
> I think your `<value/>` is not `open`?

```
<field label="Specify the access model" type="list-single" var="pubsub#access_model">
<value>presence</value>
<option label="Subscription requests must be approved and only subscribers may retrieve items"><value>authorize</value></option>
<option label="Anyone may subscribe and retrieve items"><value>open</value></option>
<option label="Anyone with a presence subscription of both or from may subscribe and retrieve items"><value>presence</value></option>
<option label="Anyone in the specified roster group(s) may subscribe and retrieve items"><value>roster</value></option>
<option label="Only those on a whitelist may subscribe and retrieve items"><value>whitelist</value></option>
</field>
```

**Comment by mwuttke97** [comment] 2021-05-31 07:28
So the issue is the following: The access model for the PEP node for the devlist was not set to `open`.
Probably, this was because Gajim created the node, and before [this commit in Gajim](https://dev.gajim.org/gajim/python-nbxmpp/-/commit/0a3564f7239e0f9423dc7f94b1c6f79da8f0929c), the access model was indeed not explicitly set to open.

So what we need to fix is: If publishing the devlist (or the bundle, for that matter) failed, try to re-configure the PEP node with the above stanza.

**Comment by DebXWoody** [comment] 2021-06-03 08:52
### Question

@g4570n Everything it working for you? Did is solve your problem?


@jubalh @mwuttke97 
Do we need to provide a fix for it? Gajim will change the access_model to open - AFAIK.
Step by step the clients and accounts will have `open` by default. I think with the warning message I have implemented + an example of a stanza to change the access_model on our website (blog) should be fine.

What do you think?

**Comment by mdosch** [comment] 2021-06-03 09:08
I fear this will lead to a lot of questions how to change the access model in the MUC and maybe even issues. How much effort would it be to set the access model to open when we publish keys?

**Comment by licaon-kter** [comment] 2021-06-03 09:31
Conversations `open`s too

**Comment by DebXWoody** [comment] 2021-06-03 12:15
We need to check if the response is  `<precondition-not-met/>`

> Preconditions MUST be processed as follows:
> 
>  If the node exists and the precondition is not met, then the publish MUST fail with a <conflict/> error condition 
> and a pubsub-specific condition of <precondition-not-met/>.

https://xmpp.org/extensions/xep-0060.html#publisher-publish-options

If it's the case, we need to process https://xmpp.org/extensions/xep-0060.html#owner-configure
( It's not "just" a stanza ;-) )

**Comment by g4570n** [comment] 2021-06-04 02:35
> ### Question
> @g4570n Everything it working for you? Did is solve your problem?

I think so

**Comment by ffuentese** [comment] 2021-06-21 20:37
Is this still solved? I still have issues talking to other people using profanity. Just now people complain that they cannot read me even if they accept my keys. I think I'm gonna ditch profanity until this issue is solved.

**Comment by mwuttke97** [comment] 2021-06-21 21:33
> Is this still solved? I still have issues talking to other people using 
> profanity. Just now people complain that they cannot read me even if 
> they accept my keys. I think I'm gonna ditch profanity until this issue 
> is solved.

(I assume you meant "is this already solved".)

Depends on what you mean by "already". I don't think the issue was 
solved in the latest release of Profanity (0.10.0). Have you tried the 
git "master" version? Lots of OMEMO issues have been resolved there.

**Comment by jubalh** [comment] 2021-06-22 07:25
> Is this still solved?

Did you read the issue? It's a bit complex to answer this question. The issue for the person is resolved, as you can see in:
"Did is solve your problem? - I think so".
Why? Because *another* client configured the nodes wrongly and @DebXWoody told the user a way to correct the nodes by sending something on Profanitys XML console. You could read that up above.

> I still have issues talking to other people using profanity. Just now people complain that they cannot read me even if they accept my keys.

In this case you need to provide more information than this. You need to tell which version you are using (if you are using git, which commit) you need to describe your problem so people can recommend things to debug and test. Otherwise no issues can get solved since for me and most people OMEMO in profanity just works. The few people that have problems need to report them and we need to fix them together. This is how this works.

**Comment by ffuentese** [comment] 2021-06-23 02:25
> In this case you need to provide more information than this. You need to tell which version you are using (if you are using git, which commit) you need to describe your problem so people can recommend things to debug and test. Otherwise no issues can get solved since for me and most people OMEMO in profanity just works. The few people that have problems need to report them and we need to fix them together. This is how this works.

I'm the OP's friend, it's the same version, same report, same machine. It doesn't work because profanity doesn't broadcast its  own fingerprint so other clients can't see it.

i talked to him from OpenBSD  with Gajim (in another computer) and he talked to me and I couldn't read his messages with OMEMO working (but he could read my messages). The only thing that's left is that there's some dependency we haven't installed.

**Comment by DebXWoody** [comment] 2021-06-23 03:52
Am Dienstag, den 22.06.2021 um 19:25:14 -0700 schrieb ***@***.***:
> I'm the OP's friend, it's the same version, same report, same
> machine. It doesn't work because profanity doesn't broadcast its
> own fingerprint so other clients can't see it.

Set your PEP item `eu.siacs.conversations.axolotl.devicelist` to open.

 1) Connect your Account with gajim
 2) Account -> Your Account -> Advanced -> PEP Configuration
 3) Select Service item `eu.siacs.conversations.axolotl.devicelist`
 4) Check the value of the access_model

"Specify the subscriber model" must bet set to `open`.

**Comment by weiss** [comment] 2021-06-29 09:31
> It's not "just" a stanza

You _could_ just [submit a configuration form][1] and only include the `pubsub#access_model` field, by the way.

However, it seems you're already [performing the full configuration form dance][2] to fix the access model for bundle nodes, so I'd think you could reuse that code?

[1]: https://xmpp.org/extensions/xep-0060.html#owner-configure-submit
[2]: https://github.com/profanity-im/profanity/blob/3c648ee2f5715998e440c316ea9eadfd8205463c/src/xmpp/omemo.c#L533-L596

**Comment by jubalh** [comment] 2021-07-26 15:27
Since more people seem to stumble upon this. Here some update:

* @paulfariello is working on this. The WIP branch can be found at https://github.com/paulfariello/profanity/tree/fix/omemo-devicelist-access-model
* We will release 0.11.1 which should fix this issue
* If you copy paste the iq stanza to fix it manually make sure you edit the line in an editor to have everything on one line (no newlines)

**Closed** 2021-08-20 13:57 UTC
Labels: bug, OMEMO

**Comment by jubalh** [comment] 2021-08-20 13:59
@g4570n @ffuentese I just merged @paulfariello PR. You can give git master a try if you still suffer from this.
A couple of more issues and we will release 0.11.1 which will contain the fix.

**Comment by fantomfp** [comment] 2022-02-20 04:49
When I began to use profanity, OMEMO was not working. Before profanity, I used other clients, with OMEMO enabled and working, in a production use-case. This is my feedback.

When I launched profanity for the first time, I followed the step described [here](https://profanity-im.github.io/guide/0111/omemo.html "Profanity User Guide for OMEMO Encryption") to enable OMEMO.

```
/omemo gen
```

After about 30 seconds, in the main window, I can see 2 errors:

```
Unable to publish own OMEMO device list, reconfiguring node
Unable to publish own OMEMO device list, previous reconfiguration failed. Giving up.
```

# Possible issue

If, and only if, OMEMO was working with other clients, perhaps your are encountering the same issue like me. If you never tried OMEMO before, please have a look in the debug log file too.

So I restarted profanity with debug enabled:

```
profanity -l DEBUG -f debug1.log
```
(then close profanity after ~2 minutes and open the log file)

In the log file, go to line:

```
16/02/2022 10:28:07: prof: ERR: [OMEMO] Unable to publish own OMEMO device list, reconfiguring node
```

Right before that line, you may have the following lines:

```
16/02/2022 10:28:07: prof: ERR: IQ error received, id: oWa6d9rMVhv7BnE36e82d2dab0187f36a20406c72dc63f0e485b829, error: conflict
16/02/2022 10:28:07: prof: ERR: [OMEMO] Publishing device list failed
```

Then, use the id to grep again. In my case the id was "oWa6d9rMVhv7BnE36e82d2dab0187f36a20406c72dc63f0e485b829".

You should get about 4 lines as result. Keep only the one with: type="error"

```
16/02/2022 10:28:07: xmpp: DBG: RECV: <iq id="oWa6d9rMVhv7BnE36e82d2dab0187f36a20406c72dc63f0e485b829" type="error" to="user@domain.tld/profanity.xxxx" lang="en" from="user@domain.tld"><pubsub xmlns="http://jabber.org/protocol/pubsub"><publish node="eu.siacs.conversations.axolotl.devicelist"><item id="current"><list xmlns="eu.siacs.conversations.axolotl"><device id="XXXXXXXXX"/><device id="XXXXX"/><device id="XXXXXXXXXX"/><device id="XXXXXXXX"/><device id="XXXXXXXXX"/></list></item></publish><publish-options><x xmlns="jabber:x:data" type="submit"><field type="hidden" var="FORM_TYPE"><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var="pubsub#access_model"><value>open</value></field></x></publish-options></pubsub><error code="409" type="cancel"><precondition-not-met xmlns="http://jabber.org/protocol/pubsub#errors"/><conflict xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/></error></iq>
```

The following line means the server is misconfigured. Sounds weird because OMEMO was working with other clients, I know.

```
code="409" type="cancel"><precondition-not-met
```

# Fix for this issue

The issue is on the server side, so the fix for that issue is in the server configuration file. If you are using ejabberd, add:

```
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: open
```

Source: https://salsa.debian.org/ejabberd-packaging-team/ejabberd/-/blob/master/debian/patches/ejabberd.yml.example.diff#L202

In my case, it was working.

# Version of profanity

0.11.1 from RPM, Fedora Linux 35

# Version of ejabberd

20.07 on server Fedora Linux 35

**Comment by paulfariello** [comment] 2022-02-20 07:14
Thanks for the detailed report. This is a permission issue, do you know what permission were set on axolotl (server side)? And which client first created the axolotl node?

**Comment by fantomfp** [comment] 2022-02-20 07:37
> Thanks for the detailed report. This is a permission issue, do you know what permission were set on axolotl (server side)? And which client first created the axolotl node?

I have no idea.
