### ISSUE TITLE
Profanity closes automatically when restarting Xorg and reattatching to tmux

### ISSUE THREAD

**Issue by dimethyltriptamine** [profanity-im/profanity#1613] opened 2021-11-08 08:49 UTC
If you run profanity in a tmux instance, restart xorg and then reattatch to the instance, profanity will be killed.

## Expected Behavior

profanity should still be running
## Current Behavior

the process is killed
## Steps to Reproduce (for bugs)

1. Create a tmux instance
2. Run profanity on it
3. Restart xorg `(doas sv down lxdm && doas sv up lxdm)` in my case
4. run `tmux a`
5. profanity is not running

## Context

Sometimes i have to restart xorg and when profanity is killed, i cannot recieve messages. 
## Environment
* Give us the version and build information output generated by `profanity -v`: `Profanity, version 0.11.1`
* If you could not yet build profanity, mention the revision you try to build from
* Operating System/Distribution: Void Linux
* glib version: 2.70

**Comment by jubalh** [comment] 2021-11-08 08:57
Duplicate of https://github.com/profanity-im/profanity/issues/1420

It includes a workaround and idea why this is happening.

**Closed by jubalh** 2021-11-08 08:57 UTC
