### ISSUE TITLE
Parse JID from URI

### ISSUE THREAD

**Issue by avidseeker** [profanity-im/profanity#1968] opened 2024-05-28 08:10 UTC
XMPP JIDs are usually shared as a URL or a URI. It would be convenient to have profanity parse it automatically. Currently, `/join editor@muc.xmpp.org` works, but
* `/join xmpp:editor@muc.xmpp.org?join`
* `/join xmpp:editor@muc.xmpp.org`
* `/join editor@muc.xmpp.org?join`

do not work.

**Comment by sjaeckel** [comment] 2024-05-28 08:14
Duplicate of #1782

**Closed by sjaeckel** 2024-05-28 08:14 UTC
Labels: duplicate
