### ISSUE TITLE
Profanity shows own messages twice in ejabberd mucs

### ISSUE THREAD

**Issue by mdosch** [profanity-im/profanity#1223] opened 2019-11-08 14:01 UTC
Own messages to a muc hosted on ejabberd are shown twice in profanity.

## Expected Behavior
Show own messages only once.

## Current Behavior
Own messages are shown twice.

## Environment

```
profanity --version
Profanity, version 0.7.1dev.master.b13ef584
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1-unknown)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (2.7.17)
GTK icons: Enabled
```

**Comment by jubalh** [comment] 2019-11-08 14:05
The problem is that in _handle_groupchat() we look for STANZA_NS_STABLE_ID which will result in origin-id or stanza-id.
It seems like prosody servers send origin-id first, so this worked in all my tests. But actually we cannot be sure of the order.
So far we stopped after the first element was found.

I only found xmpp_stanza_get_child_by_ns() and xmpp_stanza_get_child_by_name() in libstrophe. But we need a combination of both.

So I created stanza_get_child_by_name_and_ns() for Profanity. I need to remember to upstream this to libstrophe later (if they really don't have such a function).

**Comment by jubalh** [comment] 2019-11-08 14:07
@mdosch I pushed a fix to master. Please verify that it works :)

**Closed** 2019-11-08 14:06 UTC
Labels: bug

**Comment by mdosch** [comment] 2019-11-08 14:15
I can confirm it is working. Thank you. :)
