### ISSUE TITLE
unable to reconnect after re-rising network

### ISSUE THREAD

**Issue by vinegret** [profanity-im/profanity#1743] opened 2022-08-02 17:44 UTC
After getting SSL_ERROR_SYSCALL(5) with errno=110 or errno104 I can no longer connect to both with default account or with other accounts to other XMPP server. Only with a new profanity instance is possible to connect again.
I'm not sure, but it seems that I began to notice this behavior after switching from `libmesode` to `libstrophe`.
In the debugger, I see that the libstrophe does not call a SSL_shutdown at this moment as recommended in the [docs. But i still get described there bug.
](https://www.openssl.org/docs/man1.1.1/man3/SSL_get_error.html) 

## Expected Behavior

Successful recconect

## Current Behavior

[profanity.log](https://github.com/profanity-im/profanity/files/9244239/profanity.log)

## Steps to Reproduce (for bugs)

1. successfully connect to XMPP server
2. disconnect (or block connection) the network for a few minutes
3. get "Lost connection" message after re-rising network or earlier 
4. wait for a recconect automatically or forced connect manually

## Environment

```console
Profanity, version 0.12.1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 - 2021 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.17.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.10.5)
GTK icons/clipboard: Disabled
```

* Operating System/Distribution : ArchLinux
* glib2 version 2.72.3
* libstrophe version 0.12.1
* OpenSSL 1.1.1q  5 Jul 2022
* Linux 5.18.6-zen1-1-zen x86_64 GNU/Linux

**Comment by jubalh** [comment] 2022-08-03 13:46
In case you are familiar with git: does it work if you revert https://github.com/profanity-im/profanity/commit/3a03496817525d4f77f220caa813e0843797211a ?

**Comment by vinegret** [comment] 2022-08-03 14:18
@jubalh , yes, revert to 3a03496 solve this issue.

**Comment by sjaeckel** [comment] 2022-08-03 14:23
> @jubalh , yes, revert to [3a03496](https://github.com/profanity-im/profanity/commit/3a03496817525d4f77f220caa813e0843797211a) solve this issue.

do you mean 'revert of'?

**Comment by vinegret** [comment] 2022-08-03 14:32
@sjaeckel  yes, revert of 3a03496 (only revert this commit). Thanks for correcting!

**Comment by sjaeckel** [comment] 2022-08-06 17:01
I only now realized that you're hitting https://github.com/strophe/libstrophe/pull/211 ... reverting 3a03496817525d4f77f220caa813e0843797211a simply tears down the complete connection object which isn't necessary, but also solves this problem!

Can you try to build&use libstrophe from master? Otherwise you'll have to wait whether the Arch maintainers will include the necessary patch. I've just sent them an E-Mail and asked them to do so.

**Comment by jubalh** [comment] 2022-08-06 19:27
openSUSE has the mentioned PR added as a patch to the package. But I doubt all distros will know about this. Maybe there should be a new point release for libstrophe?

**Comment by sjaeckel** [comment] 2022-08-06 20:33
I'll do a 0.12.2 as soon as https://github.com/strophe/libstrophe/pull/214 is confirmed and merged

**Comment by vinegret** [comment] 2022-08-07 05:03
> I only now realized that you're hitting [strophe/libstrophe#211](https://github.com/strophe/libstrophe/pull/211) ... reverting [3a03496](https://github.com/profanity-im/profanity/commit/3a03496817525d4f77f220caa813e0843797211a) simply tears down the complete connection object which isn't necessary, but also solves this problem!
> 
> Can you try to build&use libstrophe from master? Otherwise you'll have to wait whether the Arch maintainers will include the necessary patch. I've just sent them an E-Mail and asked them to do so.

I'm sorry, I didn't pay attention to this PR before reporting.
Now, with [strophe/libstrophe#master](https://github.com/strophe/libstrophe/tree/master)  profanity working as expected.  Thanks!

**Comment by jubalh** [comment] 2022-08-08 09:34
I'll close this now here since one could argue that it's more a libstrophe issue.
Hopefully users who encounter this can find the bug and either then get the new libstrophe release (or distros patching it).

**Closed** 2022-08-08 09:34 UTC
Labels: bug, depends-on-libstrophe

**Comment by jubalh** [comment] 2022-08-08 10:51
libstrophe 0.12.2 got released: https://github.com/strophe/libstrophe/releases/tag/0.12.2
