### ISSUE TITLE
Display MUC history from log instead getting new one from server (solves OMEMO encrypted messages)

### ISSUE THREAD

**Issue by vacuumbeef** [profanity-im/profanity#1141] opened 2019-06-26 09:33 UTC
## Expected Behavior

"/omemo log on" in MUC should work the same way as it works in 1 on 1 chat.
## Current Behavior

History in MUC is encrypted after restart, even with "/omemo log on", it says "You received a message encrypted with OMEMO but your client doesn't support OMEMO." even on messages sent from profanity.

## Steps to Reproduce (for bugs)

1. Write something in MUC
2. Restart Profanity
3. See that your message is "...encrypted with OMEMO but your client doesn't support OMEMO

## Environment
Profanity, version 0.6.0dev.master.a142d3a4
Build information:
XMPP library: libmesode
Desktop notification support: Enabled
OTR support: Disabled
PGP support: Enabled (libgpgme 1.13.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.7.3)
GTK icons: Enabled

**Comment by jubalh** [comment] 2019-06-26 09:44
Thanks for the report.
OMEMO in MUC is still in experimental state, like written on https://profanity-im.github.io/omemo.html.

Each OMEMO message can only be encrypted once. But if it was encrypted and is saved to the log in cleartext then we should be able to display it.
Can you please check whether the message in question is saved in the logs (`.local/share/profanity/chatlogs`). And whether the log already contains `You received a message encrypted with OMEMO but your client doesn't support OMEMO.`?

**Comment by vacuumbeef** [comment] 2019-06-26 09:50
I have checked .local/share/profanity/chatlogs, and actually log contains messages in plain text as it should be. But in Profanity, it is still encrypted.

**Comment by jubalh** [comment] 2019-06-26 09:51
@paulfariello any idea?

**Comment by vacuumbeef** [comment] 2019-06-26 10:11
Oh you know, I noticed one more thing, I don't know is it related but still.
Messages have different time in log and in client. And it happens only with MUC. 
So, for example, log says that message was sent in 16:00:29, but in Profanity it is 15:57:08

**Comment by kaffeekanne** [comment] 2019-06-26 14:14
For the initial issue, what you get after profanity restart is MUC history provided by the server, see XEP-0045 and search for history. Since you already decrypted that messages you profanity can't decrypt them again, see forward secrecy.

So what you experience is a known drawback of the current state of how profanity works without MAM. We can't just drop these "no omemo" notices since there could be some other reason why we can't decrypt and don't want to lose messages. 

@vacuumbeef could you please check your actual chatlogs on your hard disk to see, if logging in OMEMO MUCs work? See `~/.local/share/profanity/chatlogs/<your-jid>/<muc-jid>/<date>.log`?

@jubalh may decide what should/could be done about that. Load logfile and compare timestamp with history and merge messages would be neat. Real MAM would be awesome, of course.

**Comment by vacuumbeef** [comment] 2019-06-26 16:26
@kaffeekanne Thank you for clarification on what is happening.
yeah I did checked my chatlogs already, as I was asked earlier. 

> actually log contains messages in plain text as it should be. But in Profanity, it is still shown as encrypted.

**Comment by kaffeekanne** [comment] 2019-06-26 19:18
Oh sorry, did not read careful enough. Since it is more important to implement MAM some time in future i guess there won't be a fix for this issue.

**Comment by paulfariello** [comment] 2019-06-27 12:32
@vacuumbeef room history are served by server not by profanity from the log. Then server only has encrypted version of the history and you can't decrypt it twice by design.

This is the expected behavior right now.

We could store logs in a way profanity could reload them on startup.
@jubalh maybe you want to add this to a roadmap.

**Comment by vacuumbeef** [comment] 2019-06-27 13:43
@paulfariello ah right, I got it.
But at the same time, it works as I expected in 1on1 chat with omemo on.
I'm sorry If I missing something

**Comment by jubalh** [comment] 2019-06-27 13:51
> We could store logs in a way profanity could reload them on startup.

We store them like this already, it seems on MUC or OMEMO MUC they just dont get displayed but muc history that we can when we join is only displayed. I didn't check. And also actually never used `/log on` feature, so dont know really. But I assume that we dont load logs on MUC in general?

>  But at the same time, it works as I expected in 1on1 chat with omemo on.

That's right. We should make it work in both cases.

However if it's a lot of work, then I would rather wait for having MAM implemented so we can load it that way.

**Comment by jubalh** [comment] 2019-07-03 08:40
Still not sure whether we will do this, or spend the time on MAM. But' lets rename it and move to 0.8.0.

**Comment by paulfariello** [comment] 2019-07-04 11:13
@jubalh reading from log would be required to be able to  show decrypted messages anyway.
So spending time on MAM won't avoid this work.

**Comment by jubalh** [comment] 2019-07-04 12:21
Will log and MAM not interfere with each other? Is it not like the user will need to decide which one to display? Will have to check how other clients do it.

**Comment by paulfariello** [comment] 2019-07-04 15:34
As long as you keep id in logs you can choose which log you display.

**Comment by jubalh** [comment] 2019-07-04 16:03
Some clients don't send IDs. I already thought about assigning each message we receive without an ID a internal ID. To do this for each ProfMessage. Because then we can also use this when we want to rewrite UI.

**Closed** 2022-06-15 12:35 UTC
Labels: OMEMO
