### ISSUE TITLE
Crash when swapping among windows 

### ISSUE THREAD

**Issue by unInstance** [profanity-im/profanity#1232] opened 2019-11-26 13:49 UTC
Any time I swap profanity window with /win command, profanity crashes and the terminal windows closes.

Linux 5.3.12-arch1-1 #1 SMP PREEMPT Wed, 20 Nov 2019 19:45:16 +0000 x86_64 GNU/Linux

Profanity, version 0.7.1dev.makepkg.f0a719d1
Copyright (C) 2012 - 2019 James Booth <boothj5web@gmail.com>.
Copyright (C) 2019 Michael Vetter <jubalh@iodoru.org>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Enabled (libotr 4.1.1)
PGP support: Enabled (libgpgme 1.13.1)
OMEMO support: Enabled
C plugins: Enabled
Python plugins: Enabled (3.8.0)
GTK icons: Enabled

**Comment by mdosch** [comment] 2019-11-26 14:15
Can you provide the dev a backtrace?
I wrote down how I do this, maybe this will work for you as well: https://blog.mdosch.de/2019/09/20/how-to-debug-a-tui-application/

**Comment by jubalh** [comment] 2019-11-26 14:43
@unInstance and write the exact commands to reproduce this too.

**Comment by unInstance** [comment] 2019-11-26 14:52
> Can you provide the dev a backtrace?
> I wrote down how I do this, maybe this will work for you as well: https://blog.mdosch.de/2019/09/20/how-to-debug-a-tui-application/

Terminal window closes as well. I use suckless terminal.



> @unInstance and write the exact commands to reproduce this too.

Just swap windows with /win

**Comment by jubalh** [comment] 2019-11-26 14:55
Closing this because exact commands to swap windows were not mentioned.

**Closed by jubalh** 2019-11-26 14:55 UTC
