### ISSUE TITLE
chat closure on autoreconnect?

### ISSUE THREAD

**Issue by anonproject** [profanity-im/profanity#1275] opened 2020-02-24 05:07 UTC
Let me describe my user experience.  I think it would describe the issue more clearly. :)

So I am starting the profanity via torsocks.  Then doing /msg buddy@jabber.io and /pgp start.  Then I am going to sleep.  Then I am receiving the encrypted message from my buddy and some time later the connection interruption inevitably occur.  At that moment the profanity writes in the chat window ** Lost Connection **. Then autoreconnect feature is connecting to the server and upon successful connect it closes the chat window.  I am waking up and have no way to know what the message from my buddy was.

I mean... is that supposed to be this way?

**Comment by wstrm** [comment] 2020-02-24 09:57
Hm, no this doesn't sound right.

Which version of Profanity are you running, and on which platform?

**Comment by anonproject** [comment] 2020-02-24 14:50
> Hm, no this doesn't sound right.
> 
> Which version of Profanity are you running, and on which platform?

profanity v0.8.1
CentOS 8

**Comment by jubalh** [comment] 2020-03-08 08:45
Does this happen to you too when you don't use tor? I can't reproduce this.

**Comment by anonproject** [comment] 2020-03-09 00:49
> Does this happen to you too when you don't use tor? I can't reproduce this.

Nope, didn't happen w/o tor.

**Comment by anonproject** [comment] 2020-03-11 13:48
Apparently it starts with this:
```text
11/03/2020 05:38:02: tls: DBG: error=5 errno=0
11/03/2020 05:38:02: xmpp: DBG: Unrecoverable TLS error, 5.
11/03/2020 05:38:02: xmpp: DBG: Closing socket.
11/03/2020 05:38:02: prof: DBG: Connection handler: XMPP_CONN_DISCONNECT
11/03/2020 05:38:02: prof: DBG: Connection handler: Lost connection for unknown reason
11/03/2020 05:38:02: prof: INF: Closing connection
11/03/2020 05:38:14: prof: DBG: Attempting reconnect with account uui@xxx.nl
11/03/2020 05:38:14: prof: INF: Connecting as uui@xxx.nl/profanity
11/03/2020 05:38:14: xmpp: DBG: SRV lookup failed, connecting via domain.
11/03/2020 05:38:15: xmpp: DBG: sock_connect() to xxx.nl:5222 returned 7
11/03/2020 05:38:15: xmpp: DBG: Attempting to connect to xxx.nl
11/03/2020 05:38:15: xmpp: DBG: connection successful
```

Then it reconnects successfully, but the chat window somehow getting closed (I can't find anything related to it in the logs).

If I am to specify reconnect interval = 0 then disconnect happens but the chat window is still there with a message "Lost connection". So somehow the window getting closed on reconnect.

**Comment by jubalh** [comment] 2020-03-11 13:56
Interesting. I have seen this stacktrace a couple of times in recent weeks.
More people suffer from this problem.
I don't know yet why it happens. If anybody has ideas...

The closing of chat window is very strange. It was once the case in a later version of profanity. but not in newer versions..

**Comment by anonproject** [comment] 2020-03-11 18:23
Well, in case with torsocks it is kinda clear why it happens.  It is establishing a connection through three servers on tor network.  So sometimes it happens that one of the servers is getting offline and the connection of profanity to the jabber server gets interrupted.

Why it closed the chat window on reconnection - I have no idea.  Is there any way to debug it?

**Comment by DebXWoody** [comment] 2020-04-25 08:15
There are two use cases, maybe profanity supports just one.

The user decides to disconnect from the XMPP server and and decides to connect. It could be, that the user decides to connect with another account. This means, profanity is in another context. Profanity should close all rooms / windows / sessions / ... to make sure, hat profanity is in a clean state to be able to connect to another account.

The second use case is a reconnect because of an technical issue (e.g. lost connection, suspend...). In this case, the context of the profanity session is still the same as before. There is no need to close the windows.

I the developer team agrees on that, we should make a new issue "Rework reconnecting" and see if this will solve your issue.

**Comment by mdosch** [comment] 2020-12-16 14:06
I'm also using profanity over TOR  (via proxychains4) and didn't see it closing chat windows.

**Comment by jubalh** [comment] 2020-12-16 14:15
Awesome!

**Closed by jubalh** 2020-12-16 14:15 UTC
