### ISSUE TITLE
Handle non UTF-8 encodings

### ISSUE THREAD

**Issue by srikiraju** [profanity-im/profanity#248] opened 2013-10-15 21:06 UTC
profanity doesn't take any input in fish shell. No cursor, input appears on the screen. UI doesn't respond to the inputs either, so it a total input failure.

Tested on Ubuntu 13.04 with fish shell 2.0

**Comment by jubalh** [comment] 2020-07-09 15:13
An OpenBSD user just messaged me that Profanity 0.9.5 crashes for him.
Following info:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000adaa4e2c527 in utf8_display_len (str=0xadd9b805ff0 "ï¿½") at src/common.c:216
216	    while (*curr != '\0') {
(gdb) bt 15
#0  0x00000adaa4e2c527 in utf8_display_len (str=0xadd9b805ff0 "ï¿½") at src/common.c:216
#1  0x00000adaa4e50887 in _win_print_wrapped (win=0xadcf45af500, message=0xadd42ceee50 "ï¿½\237\230\200", indent=11, pad_indent=0) at src/ui/window.c:1656
#2  0x00000adaa4e50537 in _win_print_internal (window=0xadd2d3e0800, show_char=0xadd42cee360 "-", pad_indent=0, time=0xadda1d7f4a0, flags=1, 
    theme_item=THEME_TEXT_THEM, from=0xadd5ea62b10 "butcher", message=0xadd42ceee50 "ï¿½\237\230\200", receipt=0x0) at src/ui/window.c:1583
#3  0x00000adaa4e50f26 in win_redraw (window=0xadd2d3e0800) at src/ui/window.c:1766
#4  0x00000adaa4e4e6ae in _win_correct (window=0xadd2d3e0800, message=0xadd89447a00 "[REDACTED] ï¿½\237\230\200", 
    id=0xadd0387ec40 "dd531f3f-56fa-471c-a53d-74d310936f87", replace_id=0xadd0387e580 "01b87fb1-5736-4c4e-baa1-ed422c3d3cc4", 
    from_jid=0xadd574d6c80 "muc@server.tld/someone") at src/ui/window.c:1122
#5  0x00000adaa4e4e9a9 in win_println_incoming_muc_msg (window=0xadd2d3e0800, show_char=0xadd4d837810 "-", flags=0, message=0xadd01973080) at src/ui/window.c:1181
#6  0x00000adaa4e68441 in mucwin_incoming_msg (mucwin=0xadd2d3e0800, message=0xadd01973080, mentions=0x0, triggers=0x0, filter_reflection=0) at src/ui/mucwin.c:568
#7  0x00000adaa4e67b24 in mucwin_history (mucwin=0xadd2d3e0800, message=0xadd01973080) at src/ui/mucwin.c:373
#8  0x00000adaa4e48fd4 in sv_ev_room_history (message=0xadd01973080) at src/event/server_events.c:295
#9  0x00000adaa4e3c6bb in _handle_groupchat (stanza=0xadd01f78580) at src/xmpp/message.c:914
#10 0x00000adaa4e3ae33 in _message_handler (conn=0xadd6c699000, stanza=0xadd01f78580, userdata=0xadd9c05c100) at src/xmpp/message.c:129
#11 0x00000add45c24015 in handler_fire_stanza () from /usr/local/lib/libmesode.so.0.0
#12 0x00000add45c20c65 in _handle_stream_stanza () from /usr/local/lib/libmesode.so.0.0
#13 0x00000add45c304c5 in _end_element () from /usr/local/lib/libmesode.so.0.0
#14 0x00000adce5b87338 in doContent (parser=0xadd6c6b0000, startTagLevel=0, enc=0xadce5b8eae8, s=Variable "s" is not available.
) at /usr/src/lib/libexpat/lib/xmlparse.c:2656
(More stack frames follow...)
```

```
$ locale charmap
US-ASCII
```

``
$ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_MESSAGES="C"
LC_ALL=
```

**Comment by errhammr** [comment] 2020-07-13 10:46
Setting the locale to something with UTF-8 seemed to help with the OpenBSD issue @jubalh described.

```
$ locale charmap
UTF-8
```

```
$ locale | sed 's/de_DE/en_US/'
LANG=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_CTYPE=en_US.UTF-8
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=
```

It seems to me that OpenBSD doesn't like unicode characters when it isn't told to expect them.

**Comment by jubalh** [comment] 2022-04-01 10:44
@paulfertser do you maybe have an idea about this one?

**Comment by jubalh** [comment] 2022-04-04 21:53
@paulfertser wanted to take a look at this and asked in the MUC how to reproduce it. Since for him it worked. The two people who suffered from this seemed to not know how or didn't have the time.
So closing this.

**Closed by jubalh** 2022-04-04 21:53 UTC
Labels: bug, complex
