### ISSUE TITLE
Crash after "OMEMO: missing device list for <jid>"

### ISSUE THREAD

**Issue by pmaziere** [profanity-im/profanity#1228] opened 2019-11-14 18:10 UTC
When receiving a message from a jid using sendxmpp 1.23 from debian stretch, profanity 46fd7150e5e22f986b151ef01eaffa673cff9f1e crashes with this message:

```
prof: INF: OMEMO: start session with <jid>
prof: INF: OMEMO: missing device list for <jid>
```
my OMEMO policy is set to always, but of course, sendxmpp is not OMEMO aware and does not have any OMEMO fingerprints. It was not a problem until recently, but I can't point out before which commit. I guess somewhere around the 0.7.0 release, but no guaranty, sorry.

Profanity should at least not crash and inform that something is wrong with this message.
I expect that it displays the message in the appropriate window as a non encrypted message.

Thanks for having a look at this bug

**Comment by paulfariello** [comment] 2020-01-11 21:04
Hi,

Thanks for reporting the issue.
Could you provide a stack trace corresponding to the crash?
I can't reproduce it.

**Comment by jubalh** [comment] 2020-01-12 13:53
Two more users in the MUC reported that they cannot reproduce this. Going to close this. Feel free to reopen with more details.

**Closed by jubalh** 2020-01-12 13:53 UTC
Labels: OMEMO, bug
